### ISSUE TITLE
Set のサンプル

### ISSUE THREAD

**Issue by devlights** [devlights/try-java#39]
# Tasks

- [x] Create
- [x] Empty
- [x] Add
- [x] Remove
- [x] RemoveIf
- [x] Loop
- [x] Contains
- [x] 和集合(Union) (addAll)
- [x] 積集合(Intersection) (retainAll)
- [x] 差集合(Difference) (removeAll)
- [x] 対象差(Symmetric Difference)
  - https://stackoverflow.com/questions/393968/java-is-there-an-easy-quick-way-to-and-or-or-xor-together-sets
  - https://docs.oracle.com/javase/tutorial/collections/interfaces/set.html
  - https://www.atmarkit.co.jp/ait/articles/1906/25/news015_3.html
